apiVersion: apps/v1
kind: Deployment
metadata:
  name: musecareer-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musecareer-backend
  template:
    metadata:
      labels:
        app: musecareer-backend
    spec:
      containers:
      - name: backend
        image: docker.io/boikanyomz/musecareer-backend:YOUR_TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GEMINI_BASE_URL
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: GEMINI_BASE_URL
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: GEMINI_API_KEY
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
