apiVersion: apps/v1
kind: Deployment
metadata:
  name: musecareer-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musecareer-frontend
  template:
    metadata:
      labels:
        app: musecareer-frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/boikanyomz/musecareer-frontend:b05c278
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
