apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
type: Opaque
stringData:
  GEMINI_API_KEY: "AIzaSyD7H5_Ux4psY52qJ7txZxCiYAF11TLICtI"
  GEMINI_BASE_URL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
